name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: "Build wheels"
        uses: pypa/cibuildwheel@v2.18.1
        with:
          package-dir: .
        env:
          CIBW_BEFORE_BUILD: pip install numpy cython
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_SKIP: "pp* *musllinux*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_TEST_SKIP: "*_arm64"
          CIBW_TEST_COMMAND: python {package}/tests/test_jenks.py

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
